version: '3.8'

services:
  frontendAdmin:
    #
    build: ../frontend
    image: frontend-admin
    ports:
      - 3000:80

  frontendUser:
    #
    build: ../frontend-user
    image: frontend-user
    ports:
      - 3002:80

  web:
    image: nginx
    restart: always
    volumes:
      # - ./nginx/api:/etc/nginx/sites-enabled/api
      # - ./nginx/api:/etc/nginx/sites-available/api
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/proxy:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
      - backend
      - frontendAdmin
      - frontendUser
  
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - ./cloud:/var/lib/postgresql/data/:rw
    ports:
      - "5432:5432"

  backend:
    depends_on:
      - db
    build: ../backend
    ports:
      - '8080:8080'
    stdin_open: true
    tty: true

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - '80:80'
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     # - frontend
  #     - backend

volumes:
  db:
    