version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - ./cloud:/var/lib/postgresql/data/:rw
    ports:
      - "5432:5432"
    restart: unless-stopped

  frontendadmin:
    #
    build: ../frontend
    image: frontend-admin
    ports:
      - 80:80
    restart: unless-stopped

  frontenduser:
    #
    build: ../frontend-user
    image: frontend-user
    ports:
      - 80:80
    restart: unless-stopped

  backend:
    depends_on:
      - db
    build: ../backend
    ports:
      - '80:8080'
    # stdin_open: true
    # tty: true
    restart: unless-stopped

  web:
    image: nginx
    restart: unless-stopped
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx/api:/etc/nginx/sites-enabled/api
      # - ./nginx/api:/etc/nginx/sites-available/api
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx/proxy:/etc/nginx/conf.d
      # - ./nginx/proxy.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
      - backend
      - frontendadmin
      - frontenduser

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - '80:80'
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     # - frontend
  #     - backend

volumes:
  db:
    