version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - ./cloud:/var/lib/postgresql/data/:rw
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - data-network
  # run service proxy index.js port 3000
  proxy:
    build: ./proxy
    container_name: proxy
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - data-network
  web:
    container_name: web
    image: nginx
    restart: unless-stopped
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      # - db
      - proxy
      - db
    networks:
      - data-network

volumes:
  db:
    
networks:
  data-network: