version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - ./cloud:/var/lib/postgresql/data/:rw
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  db:
    